# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc98830c83e0af09ea740981b679267384d4646a41df9271fea4fd3719251dd2838cca29b8183c25455a6da78a7c984e3c4ac360e775fd4b299a60d7bc29ca4

test:
  secret_key_base: 05341d460a25e796594184a7f2ea420e3bb30309d9f514b9804b7a519c1193617ab9799907b5e0e3c4d939a56becaf26010c77fc2ceb02d3302b26f7ae0495d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
